implementacao/pmm-web/src/main/java/br/com/pmm/primefaces/model/ChartModel.java
package br.com.pmm.primefaces.model;

import org.primefaces.event.ItemSelectEvent;
import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.BarChartModel;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.PieChartModel;
import org.springframework.stereotype.Service;


@Service
public class ChartModel {
    private BarChartModel barModel;
    private PieChartModel pieModel;
 
    public ChartModel() {
        createBarModel();
        createPieModel();
    }
 
    public BarChartModel getBarModel() {
        return barModel;
    }
     
    public PieChartModel getPieModel1() {
        return pieModel;
    }
      
    private void createBarModel() {
        barModel = initBarModel();
         
        barModel.setTitle("Bar Chart");
        barModel.setLegendPosition("ne");
         
        Axis xAxis = barModel.getAxis(AxisType.X);
        xAxis.setLabel("Gender");
         
        Axis yAxis = barModel.getAxis(AxisType.Y);
        yAxis.setLabel("Births");
        yAxis.setMin(0);
        yAxis.setMax(200);
    }
     
    private BarChartModel initBarModel() {
        BarChartModel model = new BarChartModel();
 
        ChartSeries boys = new ChartSeries();
        boys.setLabel("Boys");
        boys.set("2004", 120);
        boys.set("2005", 100);
        boys.set("2006", 44);
        boys.set("2007", 150);
        boys.set("2008", 25);
 
        ChartSeries girls = new ChartSeries();
        girls.setLabel("Girls");
        girls.set("2004", 52);
        girls.set("2005", 60);
        girls.set("2006", 110);
        girls.set("2007", 135);
        girls.set("2008", 120);
 
        model.addSeries(boys);
        model.addSeries(girls);
         
        return model;
    }
 

     
    private void createPieModel() {
        pieModel = new PieChartModel();
         
        pieModel.set("A Caminho", 10);
        pieModel.set("Entregue", 20);
        pieModel.set("Atrasados", 15);
      

        pieModel.setShowDataLabels(true);
        pieModel.setTitle("Gráfico dos Pacotes");
        pieModel.setLegendPosition("w");
    }
 
    public void itemSelect(ItemSelectEvent event) {
    	
    	System.out.println("Item Index: " + event.getItemIndex() + ", Series Index:" + event.getSeriesIndex());
    	if(event.getItemIndex() == 0){
    		System.out.println("A Caminho");
    	}
    	else if(event.getItemIndex() == 1){
    		System.out.println("Entregue");
    	}
    	else{
    		System.out.println("Atrasados");
    	}

    }
}

implementacao/pmm-web/src/main/java/br/com/pmm/primefaces/model/DashboardModel.java
package br.com.pmm.primefaces.model;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.primefaces.event.DashboardReorderEvent;
import org.primefaces.model.DashboardColumn;
import org.primefaces.model.DefaultDashboardColumn;
import org.primefaces.model.DefaultDashboardModel;


/**
 * @author Marcos
 * Classe modelo para o Dashboard
 */

public class DashboardModel {
	private org.primefaces.model.DashboardModel  model;

	public DashboardModel() {
		model = new DefaultDashboardModel();
		
		//Criando colunas do dashboard
		DashboardColumn column1 = new DefaultDashboardColumn();
		DashboardColumn column2 = new DefaultDashboardColumn();
		DashboardColumn column3 = new DefaultDashboardColumn();

		/*
		 * Adicionando os Widgets nas colunas iniciaisO valor a ser passado no
		 * método addWidget deve ser o id do p:panel na pagina home
		 */
		column1.addWidget("graphic");
		column2.addWidget("packageList");
		column3.addWidget("schedule");

		//Adicionando as colunas no dashboard
		model.addColumn(column1);
		model.addColumn(column2);
		model.addColumn(column3);
		model.addColumn(new DefaultDashboardColumn());

	}

	/*Método que será acionado ao mudar um componente de lugar no dashboard*/
	public void handleReorder(DashboardReorderEvent event) {
		//TODO mudar implementação, colocar o que é necessário (salvar posição etc...)
		FacesMessage message = new FacesMessage();
		message.setSeverity(FacesMessage.SEVERITY_INFO);
		message.setSummary("Reordered: " + event.getWidgetId());
		message.setDetail("Item index: " + event.getItemIndex()
				+ ", Column index: " + event.getColumnIndex()
				+ ", Sender index: " + event.getSenderColumnIndex());

		addMessage(message);
	}

	private void addMessage(FacesMessage message) {
		FacesContext.getCurrentInstance().addMessage(null, message);
	}

	public org.primefaces.model.DashboardModel getModel() {
		return model;
	}
}

implementacao/pmm-web/src/main/java/br/com/pmm/primefaces/model/DataTablePackagesModel.java
package br.com.pmm.primefaces.model;

import java.util.List;

import javax.faces.model.ListDataModel;

import org.primefaces.event.SelectEvent;
import org.primefaces.model.SelectableDataModel;

import br.com.semavize.pmm.mailpackage.model.Package;

public class DataTablePackagesModel extends ListDataModel<Package> implements
		SelectableDataModel<Package> {
	
	private Package pkg;

	public DataTablePackagesModel(List<Package> packagelist) {
		super(packagelist);
	}

	@SuppressWarnings("unchecked")
	@Override
	public Package getRowData(String rowKey) {

		List<Package> listMember = (List<Package>) getWrappedData();

		for (Package member : listMember) {
			if (member.toString().equals(rowKey))
				return member.clone();
		}
		return null;
	}

	@Override
	public Object getRowKey(Package pkg) {
		return pkg;
	}
	
	public void onRowSelect(SelectEvent event) {

		this.pkg = (Package) event.getObject();
		//TODO remover sysout
		System.out.println("Pacote com destinatário "+this.pkg.getNomeDestinatario()+" selecionado");
	}

	public Package getPkg() {
		return pkg;
	}

	public void setPkg(Package pkg) {
		this.pkg = pkg;
	}
	
	

}

implementacao/pmm-web/src/main/java/br/com/pmm/controller/CustomerDashboardBean.java
package br.com.pmm.controller;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.security.core.context.SecurityContextHolder;

import br.com.pmm.primefaces.model.ChartModel;
import br.com.pmm.primefaces.model.DashboardModel;
import br.com.pmm.primefaces.model.DataTablePackagesModel;
import br.com.semavize.pmm.customer.model.Customer;
import br.com.test.mock.PackageMock;

@ManagedBean(name="customerDashboradBean")
@SessionScoped
public class CustomerDashboardBean implements Serializable {

	/**
	 * @author Marcos
	 * Classe bean que representa o Dashboard por Usuário (Customer)
	 */
	private static final long serialVersionUID = 1L;

	private ChartModel chartModel;
	private DashboardModel dashboardModel;
	private DataTablePackagesModel dataTablePkgModel;
	private Customer customer;
	
	@PersistenceContext
	EntityManager em;
	
	
	
	@PostConstruct
	public void init(){
		
		dashboardModel   = new DashboardModel();
		
		
		/*Iniciando os modelos necessários do dashboard*/
		chartModel 	     = new ChartModel();

		
		
		//Exemplo Mock (Passar aqui uma lista de pacotes)
		PackageMock pm = new PackageMock();
		dataTablePkgModel = new DataTablePackagesModel(pm.getPackageListExample());
		//
		
		
		customer = (Customer) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
				
	}


	public DataTablePackagesModel getDataTablePkgModel() {
		return dataTablePkgModel;
	}

	public void setDataTablePkgModel(DataTablePackagesModel dataTablePkgModel) {
		this.dataTablePkgModel = dataTablePkgModel;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public ChartModel getChartModel() {
		return chartModel;
	}

	public void setChartModel(ChartModel chartModel) {
		this.chartModel = chartModel;
	}

	public DashboardModel getDashboardModel() {
		return dashboardModel;
	}

	public void setDashboardModel(DashboardModel dashboardModel) {
		this.dashboardModel = dashboardModel;
	}


		
}

implementacao/pmm-web/src/main/webapp/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>

	<h:outputStylesheet name="login.css" library="css" />

	<script>
        jQuery(function($) {
        	$('#login').submit(
        			function() {
        				var valid = true;
        				var errormsg = 'This field is required!';
        				var errorcn = 'error';

        				$('.' + errorcn, this).remove();

        				$('.required', this).each(
        						function() {
        							var parent = $(this).parent();
        							if ($(this).val() == '') {
        								var msg = $(this).attr('title');
        								msg = (msg != '') ? msg : errormsg;
        								$(
        										'<span class = "' + errorcn + '">'
        												+ msg + '</span>').appendTo(
        										parent).fadeIn('fast').click(
        										function() {
        											$(this).remove();
        										});
        								valid = false;
        							}
        							;
        						});
        				return valid;
        			});
        });
        </script>
</h:head>
<h:body>

	<form id="login" action="j_spring_security_check" method="post">

		<p:panel styleClass="loginContent">

			<center class="loginContentForm">

				<p:messages id="mensagens" showDetail="true" showSummary="false" />

				<h:panelGrid columns="1">


					<!-- <img class="profile-img" alt=""
						src="resources/images/avatar_2x.png"> -->
						<p>Colocar aqui o logo da Semaviz3</p><br/>
						

					<h:outputLabel for="j_username" value="Login: " />

					<h:inputText id="j_username" required="true" class="field required"
						title=" Digite seu Usuário " size="25" />



					<h:outputLabel for="j_password" value="Senha: " />

					<h:inputSecret id="j_password" required="true"
						class="field required" title=" Digite sua Senha " size="25" />



				</h:panelGrid>




				<h:commandButton value="Entrar" styleClass="button" />
				<p:panel rendered="#{param.erro}" showDetail="true"
					showSummary="false" styleClass="noBorder">
					<h:outputText styleClass="noBorder"
						value="Usuário ou senha incorretos!" />
				</p:panel>
			</center>


		</p:panel>




	</form>

</h:body>
</html>

implementacao/pmm-web/src/main/webapp/pages/charts/chartPackages.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head></h:head>
<h:form>
  
 
    <h:panelGrid columns="2" columnClasses="left,right" style="width:100%">
        <p:chart type="pie" model="#{customerDashboradBean.chartModel.pieModel1}" style="width:400px;height:300px">
            <p:ajax event="itemSelect" listener="#{chartBean.itemSelect}" immediate="true"/>
        </p:chart>
    </h:panelGrid>
 
</h:form>
</html>

implementacao/pmm-web/src/main/webapp/pages/datalist/dataTablePackages.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<body>

<h:form id="form" >
    
    			<p:dataTable value="#{customerDashboradBean.dataTablePkgModel}"
    			
				var="dataTablePkg" emptyMessage="" id="dataTablePkg"
				paginator="true" rows="10" paginatorPosition="bottom"
				paginatorTemplate="  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
				rowsPerPageTemplate="5,10,25" selectionMode="single" style="width:500px;heigth:500px">

				<p:ajax event="rowSelect" listener="#{customerDashboradBean.dataTablePkgModel.onRowSelect}" oncomplete="PF('dialogPckage').show()" update=":j_idt6:dialogPckage"/>

				<p:column sortBy="#{dataTablePkg.nomeDestinatario}"
					headerText="Destinatário">
					<h:outputText value="#{dataTablePkg.nomeDestinatario}" />
				</p:column>

				<p:column sortBy="#{dataTablePkg.cepDestino}"
					headerText="CEP Destino">
					<h:outputText value="#{dataTablePkg.cepDestino}"/>
				</p:column>
				
				<p:column sortBy="#{dataTablePkg.cepDeOrigem}"
					headerText="CEP Origem">
					<h:outputText value="#{dataTablePkg.cepDeOrigem}"/>
				</p:column>
				
				<p:column sortBy="#{dataTablePkg.situacaoAtual}"
					headerText="Situação Atual">
					<h:outputText value="#{dataTablePkg.situacaoAtual}"/>
				</p:column>
				

				
			</p:dataTable>
			

    
    
    
     
    
 
</h:form>
          
<p:dialog header="Informação do Pacote" widgetVar="dialogPckage" modal="true" height="100" id="dialogPckage">

      
   
      	<p:outputLabel value="#{customerDashboradBean.dataTablePkgModel.pkg}"></p:outputLabel>

      
</p:dialog> 

</body>
</html>

implementacao/pmm-web/src/main/webapp/pages/home/customerDashboard.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="../template/template.xhtml">

	<ui:define name="content">

		<!-- DashBoard -->
		<p:dashboard model="#{customerDashboradBean.dashboardModel.model}" disabled="false" rendered="true" id="dashboard">

			<!-- Evento a ser disparado ao mover um componente do dashboard -->
			<p:ajax event="reorder" listener="#{dashboradBean.dashboardModel.handleReorder}" />

			<!-- Adicionando a lista de objetos e seus status -->
			<p:panel id="packageList" header="#{bundle[label.package.list]}" toggleable="true">
				<ui:include src="/pages/datalist/dataTablePackages.xhtml" />
			</p:panel>
			
			<!-- Adicionando a agenda dos objetos -->	
			<p:panel id="schedule" header="#{bundle[label.package.schadule]}" toggleable="true">
				<ui:include src="/pages/schedulers/schedulerPackeges.xhtml" />
			</p:panel>

			<!-- Adicionando as estatisticas dos objetos -->
			<p:panel id="graphic" header="#{bundle[label.package.graphic]}" toggleable="true">
				<ui:include src="/pages/charts/chartPackages.xhtml" />
			</p:panel>
			
		</p:dashboard>

	</ui:define>

</ui:composition>

implementacao/pmm-web/src/main/webapp/pages/schedulers/schedulerPackeges.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<h:head></h:head> 
<body> 
	<p:schedule style="width:500px;heigth:400px"  ></p:schedule>
</body> 
</html>

implementacao/pmm-web/src/main/webapp/pages/template/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<!-- Importando CSS-->
	<h:outputStylesheet name="default.css" library="css" />

</h:head>

<h:body>

	<h:form>
		<!--Definindo Toolbar (menu) da pagina template -->

		<p:toolbar>
		    <f:facet name = "left">
		        <p:commandButton  value = "#{bundle['label.dashboard']}" icon = "ui-icon-calculator"/>
		        
		        <p:menuButton value="#{bundle['label.package.load']}">
	                <p:menuitem value="#{bundle['label.package.load.bynumber']}" actionListener="#"  icon="ui-icon-pencil" />
	                <p:menuitem value="#{bundle['label.package.load.byfile']}"   actionListener="#"  icon="ui-icon-document" />
            	</p:menuButton>
		        
		        <p:menuButton value="#{bundle['label.report']}" >
	                <p:menuitem value="#{bundle['label.report.package']}" actionListener="#"  icon="ui-icon-document-b" />
<!-- 	            <p:menuitem value="#{bundle[label.report]}" actionListener="#" icon="ui-icon-document-b" />
	                <p:menuitem value="#{bundle[label.report]}" actionListener="#" icon="ui-icon-document-b" />
	                <p:menuitem value="#{bundle[label.report]}" actionListener="#" icon="ui-icon-document-b" /> -->
            	</p:menuButton>
		        
		    </f:facet>
		    
		    <f:facet name = "right">
		        <p:commandButton value="#{bundle['label.logout']}" icon = "ui-icon-power" onclick = "window.open('PMM-web/logout','_self')" style = "color:red"/>
		    </f:facet>
		    
		</p:toolbar>

		<!-- Definindo um ui:insert, a pagina que tiver <ui:define name="content"> 
           	     terá seu conteúdo adicionado em template.xhtml -->
		<div class="content" id="content">
			<ui:insert name="content" />
		</div>

	</h:form>


	<div class="footer">
		<p:outputLabel value="#{bundle['label.user']}: #{customerDashboradBean.customer}" styleClass="footer_customer" />
		<p:outputLabel value="Semaviz3 ®" styleClass="footer_semavize" />
	</div>
</h:body>

</html>